name: Café Com Pão
favicon: null
layout_spectrum: 0.38311056257225573
typography_spectrum: 0.583852214505896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8676422922872007
  lightness: 0.5296038687229156
  saturation: 0.9636835330165923
  rhythmicContrast: 0.09458792535588145
purpose: []
