name: Café Com Pão
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18266
title: Café com Pão
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffc875'
    - '#361f11'
    - '#703800'
    - '#bb8848'
    - '#9d6614'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
